[feat] Separate review issues
repobee/repobee pull request #1016
Opened 2022-03-08 23:17 UTC by Adamih

#789

2022-03-09 17:32 UTC, slarse commented
Thanks @Adamih @ZinoKader, at first glance it looks like this will do the job! Nice attention to detail with the documentation as well :)

Just closing and opening again to trigger the GitLab system tests here...

2022-03-09 18:40 UTC, slarse commented
Looks like a GitLab system test needs to be updated, it expects a single issue with a static name.

2022-03-09 20:59 UTC, slarse requested changes
One of the GitLab system tests is failing as the assertion is out-of-date. It's assuming a single issue to be opened with a static name, which clearly doesn't hold after this improvement. So you need to go in there and tweak the test a bit!

2022-03-09 23:45 UTC, ZinoKader commented
I am unfortunately unable to run the GitLab system tests and it may have to do with my M1 macbook... [This is the issue](https://forum.gitlab.com/t/gitlab-ce-docker-on-apple-m1-stuck-on-recipe-gitlab-database-migrations/49297/3) I am experiencing.

2022-03-10 16:47 UTC, Adamih commented
This is the best solution I could come up with

```python
assert_num_issues(STUDENT_TEAMS, [assignment_name], 1)
# For each reviewed student
for reviewed_student in STUDENT_TEAMS:
    # Get all potential reviewing students
    reviewing_students = (
         s for s in STUDENT_TEAMS if s != reviewed_student
    )
    # Match title
    assert_issue_title_match(
        [reviewing_student],
        [assignment_name],
        "^Review issue \((?:" + "|".join(reviewing_students) + ")\)$",    # Any of potential reviewing students
    )
```

````python
def assert_issue_title_match(student_teams, assignment_names, pattern):
    def assertion(project):
        issues = project.issues.list(all=True)
        for actual_issue in issues:
            if re.match(pattern, actual_issue.title):
                return
        assert False, "no issue title matching the specified pattern"

    _assert_on_projects(student_teams, assignment_names, assertion)
```

This is the best idea I have but it still seems a bit finicky.

2022-03-11 23:16 UTC, slarse requested changes
I've been preoccupied over the past few days, hence the communications blackout.

Anyway, this looks very good, I'd rate this a very high quality PR. I have some comments on simplifications that I'd like to see and some miscellaneous stuff that you couldn't possibly have known. Overall I'm very happy with this contribution and I think we can merge once you've addressed my comments.

One more thing: this branch is out of date with the base branch, could you update it (i.e. merge master into it)?

2022-03-11 23:16 UTC, slarse commented on system_tests/gitlab/_helpers/asserts.py
> +        assert False, "no issue title matching the specified pattern"
Curious decision to put all assertions (which are integral to the tests) in a module separate from the tests. Yesterday me is full of surprises.

I'm not saying you should do anything about that, I'll open a separate issue about it.

2022-03-11 23:16 UTC, slarse commented on system_tests/gitlab/test_gitlab_system.py
> +            )
I would suggest to weaken the assertions here for the sake of simplicity. System tests are more about the bigger picture than minute details, so I think it's perfectly fine to have looser assertions than one normally would in a lower level test.

```suggestion
    assert_issue_title_match(STUDENT_TEAMS, [assignment_name], r"^Peer review.*$")
```

2022-03-11 23:27 UTC, slarse commented on system_tests/gitlab/_helpers/asserts.py
> +        assert False, "no issue title matching the specified pattern"
#1020

2022-08-28 11:19 UTC, slarse commented
Closing as stale, feel free to revisit.

2022-08-28 11:19 UTC, closed without merging