[docs] Fix typos
repobee/repobee pull request #1179
Opened 2023-09-13 04:33 UTC by kianmeng

Found via `typos --format brief`

2023-09-18 19:44 UTC, slarse requested changes
Hi! Thanks for you contribution, and sorry for the wait.

I just have one comment, one of the edits nullifies a regression test :)

2023-09-18 19:44 UTC, slarse commented on tests/unit_tests/repobee/test_main.py
> +        main.main("repbee issues -h".split())
This is intentionally misspelled as part of a regression test :)

```suggestion
        main.main("repbee isues -h".split())
```

2023-09-21 19:13 UTC, slarse approved these changes

2023-09-21 19:14 UTC, slarse commented
Thanks! Docs building is failing but that seems unrelated, so I'll merge.

2023-09-21 19:14 UTC, merged

2023-09-22 02:23 UTC, kianmeng commented
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face: